# ls-example pipeline.yml

jobs:

- name: job-ls-example
  plan:
  - get: my-cheat-sheets
    trigger: true
  - task: task-ls-example
    file: my-concourse-ci-tasks/ls-example/ci/tasks/task-ls-example.yml

resources:

- name: my-cheat-sheets
  type: git
  source:
    #uri: https://github.com/jeffdecola/my-cheat-sheets
    uri: git@github.com:jeffdecola/my-concourse-ci-tasks.git
    branch: master
    private_key: {{git_private_key}}
