# search-and-replace pipeline.yml

jobs:

- name: job-seach-and-replace
  plan:
  - get: my-cheat-sheets
    trigger: true
  - task: task-seach-and-replace
    file: my-cheat-sheets/concourse-cheat-sheet/ci/tasks/task-search-and-replace.yml

resources:

- name: my-cheat-sheets
  type: git
  source:
    #uri: https://github.com/jeffdecola/my-cheat-sheets
    uri: git@github.com:jeffdecola/my-cheat-sheets.git
    branch: master
    private_key: {{git_private_key}}
