# ls-example task-ls-example2.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: my-concourse-ci-tasks

outputs:
- name: result

run:
  path: ./my-concourse-ci-tasks/ls-example/ci/scripts/ls-example2.sh
