# concourse-cheat-sheet task-search-and-replace.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: my-cheat-sheets

outputs:
- name: result

run:
  path: ./my-cheat-sheets/concourse-cheat-sheet/ci/scripts/search-and-replace.sh
