# readme-github-pages pipeline.yml

jobs:

- name: job-readme-github-pages
  plan:
  - get: my-concourse-ci-tasks
    trigger: true
  - task: task-readme-github-pages
    file: my-concourse-ci-tasks/readme-github-pages/ci/tasks/task-readme-github-pages.yml
    on_success:
      do:
      - put: my-concourse-ci-tasks
        params:
          repository: my-concourse-ci-tasks-updated  

resources:

- name: my-concourse-ci-tasks
  type: git
  source:
    uri: git@github.com:jeffdecola/my-concourse-ci-tasks.git
    branch: master
    private_key: {{git_private_key}}
