# readme-github-pages pipeline.yml

jobs:

- name: job-readme-github-pages
  plan:
  - get: my-concourse-ci-tasks
    trigger: true
  - put: resource-slack-alert
    params:
      channel: '#jeff-builds'
      text: "From readme-github-pages: STARTED job-readme-github-pages in concourse ci."
  - put: resource-repo-status
    params: { state: "pending", description: "STARTED job-readme-github-pages in concourse ci.", commit: "readme-github-pages" }
  - task: task-readme-github-pages
    file: my-concourse-ci-tasks/readme-github-pages/ci/tasks/task-readme-github-pages.yml
    on_success:
      do:
      - put: my-concourse-ci-tasks
        params:
          repository: my-concourse-ci-tasks-updated  
      - put: resource-slack-alert
        params:
          channel: '#jeff-builds'
          text: "From readme-github-pages: PASSED job-readme-github-pages in concourse ci."
      - put: resource-repo-status
        params: { state: "success", description: "PASSED job-readme-github-pages in concourse ci", commit: "readme-github-pages" }
    on_failure:
      do:
      - put: resource-slack-alert
        params:
          channel: '#jeff-builds'
          text: "From readme-github-pages: FAILED job-readme-github-pages in concourse ci."
      - put: resource-repo-status
        params: { state: "failure", description: "FAILED job-readme-github-pages in concourse ci", commit: "readme-github-pages" }

resource_types:

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

- name: github-status
  type: docker-image
  source:
    repository: dpb587/github-status-resource
    tag: master

resources:

- name: my-concourse-ci-tasks
  type: git
  source:
    uri: git@github.com:jeffdecola/my-concourse-ci-tasks.git
    branch: master
    private_key: {{git_private_key}}

- name: resource-slack-alert
  type: slack-notification
  source:
    url: {{slack_url}}
    
- name: resource-repo-status 
  type: github-status
  source:
    repository: jeffdecola/my-concourse-ci-tasks
    access_token: {{repo_github_token}}