# readme-github-pages pipeline.yml

jobs:

- name: job-readme-github-pages
  plan:
  - get: my-concourse-ci-tasks
    trigger: true
  - task: task-readme-github-pages
    file: my-concourse-ci-tasks/readme-github-pages/ci/tasks/task-readme-github-pages.yml

resources:

- name: my-concourse-ci-tasks
  type: git
  source:
    uri: git@github.com:jeffdecola/my-concourse-ci-tasks.git
    branch: master
    private_key: {{git_private_key}}
